variables:
  GITHUB_REPO: $CI_PROJECT_NAME
  GITHUB_GROUP: enix
  PYTHONUNBUFFERED: "1"
  ANSIBLE_FORCE_COLOR: "1"
  PY_COLORS: '1'

molecule:
  stage: test
  services:
    - docker:dind
  variables:
      DOCKER_BUILDKIT: 1
      DOCKER_HOST: tcp://docker:2376
      DOCKER_TLS_CERTDIR: "/certs"
      DOCKER_TLS_VERIFY: 1
      DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
      DOCKER_DRIVER: overlay2

  image: docker:stable-dind
  before_script:
    - apk add --no-cache
      python3 python3-dev py3-pip gcc git curl build-base
      autoconf automake py3-cryptography linux-headers
      musl-dev libffi-dev openssl-dev openssh rsync
    - python3 -m pip install ansible molecule[docker] ansible-lint yamllint
    - docker info
    - python3 --version
    - ansible --version
    - ansible-lint --version
    - yamllint --version
    - molecule --version  

  script:
    - molecule test --all -- -vv
  tags:
    - docker-dind

importgalaxy:
  stage: deploy
  image: registry.gitlab.com/lcaflc/ansiblecheck:debian-bullseye
  only: 
    - main
    - master
    - tags
#  when: on_success
  before_script:
    - ansible --version
  script:
    - ansible-galaxy role import ${GITHUB_GROUP} ${GITHUB_REPO} --token ${GALAXY_API_TOKEN}
