---

- name: "Debian: Add postgresql.org repository GPG key"
  ansible.builtin.apt_key:
    url: "{{ postgresql__gpg_url }}"

- name: "Debian: Configure postgresql.org apt repository"
  ansible.builtin.apt_repository:
    repo: "{{ postgresql__apt_repo }}"
    state: present
    update_cache: yes

- name: "Debian: Install postgresql-common"
  ansible.builtin.apt:
    name: "postgresql-common"
    state: present

- name: Disable initdb
  ansible.builtin.lineinfile:
    path: /etc/postgresql-common/createcluster.conf
    regexp: "^create_main_cluster ="
    line: create_main_cluster = false
    insertafter: "^#create_main_cluster ="
    state: present
  when: postgresql__disable_initdb

- name: "Debian: Install postgresql package"
  ansible.builtin.apt:
    name: "postgresql-{{ postgresql__version }}"
    state: present
  notify:
    - Restart postgresql

- name: "Debian: Install python-psycopg2"
  ansible.builtin.apt:
    name: "python-psycopg2"
    state: present
  when: ansible_python.version.major == 2

- name: "Debian: Install python3-psycopg2"
  ansible.builtin.apt:
    name: "python3-psycopg2"
    state: present
  when: ansible_python.version.major == 3

- name: "Debian: Install postgresql extensions"
  ansible.builtin.apt:
    name: "postgresql-{{ postgresql__version }}-{{ item }}"
    state: present
  notify: Restart postgresql
  with_items: "{{ postgresql__extensions }}"

- name: "Debian: Install pgbackrest"
  ansible.builtin.apt:
    name: "pgbackrest"
    state: present
  when: postgresql__install_pgbackrest

- name: "Debian: Install pg_auto_failover"
  ansible.builtin.apt:
    name: [ "pg-auto-failover-cli", "postgresql-14-auto-failover" ]
    state: present
  when: postgresql__install_pg_auto_failover
