---

# dummy task for tests
- name: "Dummy task"
  copy:
    dest: /tmp/.dummy-ansible-task
    content: |
      {{ ansible_host }}
      ------------------
      {% if ansible_lsb is defined %}
      {{ ansible_lsb | to_nice_json }}
      {% else %}
      {{ ansible_distribution }}
      {% endif %}
