---

- name: "Checking PostgreSQL supported version"
  fail:
    msg: "Not a supported PostgreSQL version {{ postgresql__version }}"
  when: ( postgresql__version < 9 ) or ( postgresql__version > 11 )

- include_tasks: install-debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: configure.yml

- name: Ensure PostgreSQL is started and enabled on boot.
  service:
    name: postgresql
    state: started
    enabled: true


- include_tasks: create_users.yml
- include_tasks: databases.yml
- include_tasks: grant_users.yml
