# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "debian/stretch64"
  config.vm.define "debianstretch64" do |debianstretch64| end

# virtualbox provider only need a base virtualbox installation on
# the local system. This is the default if no provider requested
  config.vm.provider "virtualbox" do |v|
      v.memory = 512
      v.cpus = 1
  end

# openstack provider for Vagrant
# need vagrant-openstack-provider, See README.vagrant.md for details
# vagrant up --provider openstack
  config.vm.provider :openstack do |os, override|
    override.vm.box = "sharpie/dummy"
    override.ssh.username = 'debian'
    os.openstack_auth_url = ENV['OS_AUTH_URL']
    os.username           = ENV['OS_USERNAME']
    os.password           = ENV['OS_PASSWORD']
    os.tenant_name        = ENV['OS_TENANT_NAME']
    os.flavor             = 'GP1.XS'
    os.image              = 'Debian 9.5.5'
    os.floating_ip_pool   = ENV['OS_FLOATING_IP_POOL']
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../tests/test.yml"
    ansible.verbose = "vvv"
    ansible.sudo = true
    ansible.galaxy_role_file = "../requirements.yml"
    ansible.groups = {
      "test" => ["debianstretch64"],
      }
  end

  if Vagrant.has_plugin?("vagrant-cachier")
    # Configure cached packages to be shared between instances of the same base box.
    # More info on http://fgrehm.viewdocs.io/vagrant-cachier/usage
    config.cache.scope = :box
  end
end
