---
# handlers file for postgresql

- name: Restart postgresql
  ansible.builtin.service:
    name: postgresql
    state: restarted
  # when: ansible_virtualization_type != "docker"

- name: Reload postgresql
  ansible.builtin.service:
    name: postgresql
    state: reloaded
  # when: ansible_virtualization_type != "docker"
