---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  # - name: debian-buster
  #   image: debian:buster
  #   pre_build_image: false
  - name: debian-bullseye
    image: debian:bullseye
    pre_build_image: false
  # - name: ubuntu-focal
  #   image: ubuntu:focal
  #   pre_build_image: false
  # - name: ubuntu-jammy
  #   image: ubuntu:jammy
  #   pre_build_image: false
provisioner:
  name: ansible
  options:
   vvv: true
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
